#goal definition
string movement_type
string frame_id
bool preempt
float64 takeoff_height
float64 x_position
float64 y_position
float64 z_position
---
#result definition
bool success

---
#feedback
float64 completion
