#goal definition
string movement_type
string frame_id
bool preempt
bool hold_current_position
float64 takeoff_height
float64 time_to_track
float64 x_overshoot
float64 y_overshoot
float64 x_position
float64 y_position
float64 z_position
float64 x_velocity
float64 y_velocity
---
#result definition
bool success
---
#feedback
float64 completion
